// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "crudws": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/mrcaelumn/crudwebsocket/api/design
// --out=$(GOPATH)/src/github.com/mrcaelumn/crudwebsocket/api
// --version=v1.3.1

package test
